#!/usr/bin/env bash

_black=$(tput setaf 0)
_red=$(tput setaf 1)
_green=$(tput setaf 2)
_yellow=$(tput setaf 3)
_blue=$(tput setaf 4)
_magenta=$(tput setaf 5)
_cyan=$(tput setaf 6)
_white=$(tput setaf 7)

_blackBg=$(tput setab 0)
_redBg=$(tput setab 1)
_greenBg=$(tput setab 2)
_yellowBg=$(tput setab 3)
_blueBg=$(tput setab 4)
_magentaBg=$(tput setab 5)
_cyanBg=$(tput setab 6)
_whiteBg=$(tput setab 7)

_bold=$(tput bold)

_reset=$(tput sgr0)

export PS1="${_GREEN}\h${_BLUE}@${_RED}\u${_RESET} ${_BOLD}\$ ${_RESET}"

# default $PS1 on MacOS = \h:\W \u\$

# default $PS2 on MacOS = >

# default $PS3 on MacOS =

# default $PS4 on MacOS = +



#\u - user name
#\h - short hostname
#\W - current working dir
#\? - exit status of the command
# export PS1="{\[\e[32m\]\u\[\e[m\]@\[\e[36m\]\h\[\e[m\]:\W_\$?}$ "
