#!/usr/bin/env bash

# file for local unversioned requirements
fileBashrcLocal=~/.bashrc_local
if [ -e "$fileBashrcLocal" ]; then
  source $fileBashrcLocal
fi

# bash config
source ~/.dotfiles/shell-bash/aliases
source ~/.dotfiles/shell-bash/prompt
source ~/.dotfiles/shell-bash/settings

# run commands
source ~/.dotfiles/runcom/nvmrc
source ~/.dotfiles/runcom/utilities
