#!/usr/bin/env bash

# File for local unversioned requirements
fileBashrcLocal=~/.bashrc_local
if [ -e "$fileBashrcLocal" ]; then
  source $fileBashrcLocal
fi

# Bash config
source ~/.dotfiles/shell-bash/aliases
source ~/.dotfiles/shell-bash/paths
source ~/.dotfiles/shell-bash/prompt
source ~/.dotfiles/shell-bash/settings

# Run commands
source ~/.dotfiles/runcom/nvmrc
